"""transaction.inventaire_consomme

Revision ID: 4790a5b7512a
Revises: 7a6b54f8d20b
Create Date: 2026-07-20 02:01:40.603971
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4790a5b7512a'
down_revision: Union[str, None] = '7a6b54f8d20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('inventaire_consomme', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'inventaire_consomme')
    # ### end Alembic commands ###
