"""initial schema

Revision ID: 7a6b54f8d20b
Revises: 
Create Date: 2026-07-20 01:46:06.834397
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6b54f8d20b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forfaits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=32), nullable=False),
    sa.Column('prix', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('zones_requises', sa.JSON(), nullable=False),
    sa.Column('temps_min', sa.Integer(), nullable=False),
    sa.Column('temps_max', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('parametres',
    sa.Column('cle', sa.String(length=64), nullable=False),
    sa.Column('valeur', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('cle')
    )
    op.create_table('rapports_journaliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_vehicules', sa.Integer(), nullable=False),
    sa.Column('total_ca', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('repartition_forfaits', sa.JSON(), nullable=False),
    sa.Column('taux_conformite', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('nombre_anomalies', sa.Integer(), nullable=False),
    sa.Column('performance_employes', sa.JSON(), nullable=False),
    sa.Column('fichier_pdf', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rapports_journaliers_date'), 'rapports_journaliers', ['date'], unique=True)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaque', sa.String(length=32), nullable=False),
    sa.Column('premiere_visite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('derniere_visite', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nombre_visites', sa.Integer(), nullable=False),
    sa.Column('photo_reference', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicules_plaque'), 'vehicules', ['plaque'], unique=True)
    op.create_table('bays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('staff', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bays_site_id'), 'bays', ['site_id'], unique=False)
    op.create_table('employes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=False),
    sa.Column('badge_nfc_id', sa.String(length=64), nullable=True),
    sa.Column('couleur_gilet', sa.String(length=9), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employes_badge_nfc_id'), 'employes', ['badge_nfc_id'], unique=True)
    op.create_index(op.f('ix_employes_site_id'), 'employes', ['site_id'], unique=False)
    op.create_table('horaires_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('jour', sa.Integer(), nullable=False),
    sa.Column('heure_ouverture', sa.Time(), nullable=False),
    sa.Column('heure_fermeture', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horaires_site_site_id'), 'horaires_site', ['site_id'], unique=False)
    op.create_table('produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(length=128), nullable=False),
    sa.Column('unite', sa.String(length=16), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('seuil_alerte', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produits_site_id'), 'produits', ['site_id'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('forfait_produits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forfait_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('lavages_par_unite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['forfait_id'], ['forfaits.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forfait_produits_forfait_id'), 'forfait_produits', ['forfait_id'], unique=False)
    op.create_index(op.f('ix_forfait_produits_produit_id'), 'forfait_produits', ['produit_id'], unique=False)
    op.create_table('horaires_employe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('jour', sa.Integer(), nullable=False),
    sa.Column('debut', sa.Time(), nullable=False),
    sa.Column('fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horaires_employe_employe_id'), 'horaires_employe', ['employe_id'], unique=False)
    op.create_table('pointages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('heure', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('photo', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pointages_employe_id'), 'pointages', ['employe_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicule_id', sa.Integer(), nullable=True),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('forfait_id', sa.Integer(), nullable=True),
    sa.Column('bay_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.String(length=64), nullable=True),
    sa.Column('heure_entree', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heure_sortie', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duree_totale', sa.Integer(), nullable=True),
    sa.Column('zone_b_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zone_b_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zone_b_duree', sa.Integer(), nullable=True),
    sa.Column('zone_c_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zone_c_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zone_c_duree', sa.Integer(), nullable=True),
    sa.Column('zone_d_debut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zone_d_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zone_d_duree', sa.Integer(), nullable=True),
    sa.Column('forfait_detecte', sa.String(length=32), nullable=True),
    sa.Column('conforme', sa.Boolean(), nullable=True),
    sa.Column('photo_entree', sa.String(length=512), nullable=True),
    sa.Column('photo_sortie', sa.String(length=512), nullable=True),
    sa.Column('statut', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bay_id'], ['bays.id'], ),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['forfait_id'], ['forfaits.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_bay_id'), 'transactions', ['bay_id'], unique=False)
    op.create_index(op.f('ix_transactions_statut'), 'transactions', ['statut'], unique=False)
    op.create_index(op.f('ix_transactions_track_id'), 'transactions', ['track_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('severite', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('heure', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('photo', sa.String(length=512), nullable=True),
    sa.Column('notifie', sa.Boolean(), nullable=False),
    sa.Column('resolu', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_severite'), 'anomalies', ['severite'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forfait_id', sa.Integer(), nullable=False),
    sa.Column('prix', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('plaque', sa.String(length=32), nullable=True),
    sa.Column('employe_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('heure', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('statut', sa.String(length=16), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.ForeignKeyConstraint(['forfait_id'], ['forfaits.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_plaque'), 'tickets', ['plaque'], unique=False)
    op.create_index(op.f('ix_tickets_statut'), 'tickets', ['statut'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_statut'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_plaque'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_anomalies_severite'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_transactions_track_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_statut'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_bay_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_pointages_employe_id'), table_name='pointages')
    op.drop_table('pointages')
    op.drop_index(op.f('ix_horaires_employe_employe_id'), table_name='horaires_employe')
    op.drop_table('horaires_employe')
    op.drop_index(op.f('ix_forfait_produits_produit_id'), table_name='forfait_produits')
    op.drop_index(op.f('ix_forfait_produits_forfait_id'), table_name='forfait_produits')
    op.drop_table('forfait_produits')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_produits_site_id'), table_name='produits')
    op.drop_table('produits')
    op.drop_index(op.f('ix_horaires_site_site_id'), table_name='horaires_site')
    op.drop_table('horaires_site')
    op.drop_index(op.f('ix_employes_site_id'), table_name='employes')
    op.drop_index(op.f('ix_employes_badge_nfc_id'), table_name='employes')
    op.drop_table('employes')
    op.drop_index(op.f('ix_bays_site_id'), table_name='bays')
    op.drop_table('bays')
    op.drop_index(op.f('ix_vehicules_plaque'), table_name='vehicules')
    op.drop_table('vehicules')
    op.drop_table('sites')
    op.drop_index(op.f('ix_rapports_journaliers_date'), table_name='rapports_journaliers')
    op.drop_table('rapports_journaliers')
    op.drop_table('parametres')
    op.drop_table('forfaits')
    # ### end Alembic commands ###
